config/routes.rb
Rails.application.routes.draw do
root 'restaurants#index'
resources :restaurants, only:[:index, :show, :create, :new] do
resources :reviews, only:[:create, :new]
end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  validates :name, presence:true
  validates :address, presence:true
  validates :city, presence:true
  validates :state, presence:true
  validates :zipcode, presence:true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  validates :body, presence:true
  validates :rating, :inclusion => 1..5, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
  @restaurants = Restaurant.all.order(created_at: :desc).limit(10)
  #order them by when they were updated, show only 10
  end

  def show
  @restaurant = Restaurant.find(params[:id])
  @reviews = Review.all.order(created_at: :desc).where(restaurant_id:"#{@restaurant.id}")
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
      if @restaurant.save
        redirect_to @restaurant
      else
      flash[:notice] = "Please enter all fields with a rating between 1-5"
      render :new
      end
  end

private

def restaurant_params
  params.require(:restaurant).permit(:name,:address,:city,:state,:zipcode,:description, :category)

end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    id = @restaurant.id
    @review = Review.new(review_params)
    @review.restaurant_id = id
    if @review.save
      redirect_to @restaurant
    else
     render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:body,:rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<div class = "restaurant-info">
<h1>Restaurants in Boston</h1>
<ul>
<% @restaurants.each do |restaurant| %>
<li><h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3></li>
<% end %>
</ul>

<p><%= link_to 'Add a new restaurant', new_restaurant_path(@restaurant) %></p>

</div>

app/views/restaurants/new.html.erb
<div class = "restaurant-info">

<h1> Tell us about your Restaurant </h1>
<%= form_for @restaurant do |f| %>

<% if @restaurant.errors.any? %>
<h2>Errors </h2>
<ul>
<% @restaurant.errors.full_messages.each do |message|%>
<li><%= message %> </li>
<%end%>
</ul>
<%end%>

 <%= f.label :name %>
 <%= f.text_field :name, required: true %>

<%= f.label :address %>
<%= f.text_field :address, required: true%>

<%= f.label :city %>
 <%= f.text_field :city, required: true %>

<%= f.label :state %>
<%= f.text_field :state, required: true %>

<%= f.label :zipcode%>
<%= f.text_field :zipcode, required: true%>

<%= f.label :description%>
<%= f.text_area :description%>

<%= f.label :category %>
<%= f.text_field :category%>

<%= f.submit 'Submit'%>
<% end %>

<%= link_to 'Back', root_url %>
</div>

app/views/restaurants/show.html.erb
<div class = "restaurant-info">
<h1><%=@restaurant.name %></h1>

<h4> <%= @restaurant.category %></h4>

<h4> <%= @restaurant.address %>, <%= @restaurant.city %>, <%=@restaurant.state %> <%=@restaurant.zipcode%> </h4>

<p id= "description"> - <%= @restaurant.description %> - </p>
</div>

<h3> Reviews</h3>

<p><%= link_to 'Add a new review', new_restaurant_review_path(@restaurant) %></p>

<% @reviews.each do |review| %>
<div class = "reviews">
<p><%= review.body %></p>
<h5> Score: <%= review.rating %> </h5>
<%end%>
</div>
<%= link_to 'Back', root_url %>

app/views/reviews/new.html.erb
<div class = "restaurant-info">
<h3> Would you like to submit a review for <%= @restaurant.name %>? </h3>

<%= form_for [@restaurant, @review], :url => restaurant_reviews_path do |f| %>

<% if @review.errors.any? %>
<h2>Errors </h2>
<ul>
<% @review.errors.full_messages.each do |message|%>
<li><%= message %> </li>
<%end%>
</ul>
<%end%>

 <%= f.label :rating%>
 <%= f.text_field :rating, required: true %>

<%= f.label :body %>
<%= f.text_field :body, required: true%>

<%= f.submit 'Submit'%>
<% end %>

<%= link_to 'Back', @restaurant  %>
</div>